export type Country = {
  code: string;
  dial: string;
  name: string;
};

// Dial codes with no `+`; codes are ISO 3166-1 alpha-2, names are the
// short English form. Sorted by name.
export const COUNTRIES: Country[] = [
  { code: 'AF', dial: '93', name: 'Afghanistan' },
  { code: 'AL', dial: '355', name: 'Albania' },
  { code: 'DZ', dial: '213', name: 'Algeria' },
  { code: 'AS', dial: '1', name: 'American Samoa' },
  { code: 'AD', dial: '376', name: 'Andorra' },
  { code: 'AO', dial: '244', name: 'Angola' },
  { code: 'AI', dial: '1', name: 'Anguilla' },
  { code: 'AG', dial: '1', name: 'Antigua and Barbuda' },
  { code: 'AR', dial: '54', name: 'Argentina' },
  { code: 'AM', dial: '374', name: 'Armenia' },
  { code: 'AW', dial: '297', name: 'Aruba' },
  { code: 'AU', dial: '61', name: 'Australia' },
  { code: 'AT', dial: '43', name: 'Austria' },
  { code: 'AZ', dial: '994', name: 'Azerbaijan' },
  { code: 'BS', dial: '1', name: 'Bahamas' },
  { code: 'BH', dial: '973', name: 'Bahrain' },
  { code: 'BD', dial: '880', name: 'Bangladesh' },
  { code: 'BB', dial: '1', name: 'Barbados' },
  { code: 'BY', dial: '375', name: 'Belarus' },
  { code: 'BE', dial: '32', name: 'Belgium' },
  { code: 'BZ', dial: '501', name: 'Belize' },
  { code: 'BJ', dial: '229', name: 'Benin' },
  { code: 'BM', dial: '1', name: 'Bermuda' },
  { code: 'BT', dial: '975', name: 'Bhutan' },
  { code: 'BO', dial: '591', name: 'Bolivia' },
  { code: 'BA', dial: '387', name: 'Bosnia and Herzegovina' },
  { code: 'BW', dial: '267', name: 'Botswana' },
  { code: 'BR', dial: '55', name: 'Brazil' },
  { code: 'VG', dial: '1', name: 'British Virgin Islands' },
  { code: 'BN', dial: '673', name: 'Brunei' },
  { code: 'BG', dial: '359', name: 'Bulgaria' },
  { code: 'BF', dial: '226', name: 'Burkina Faso' },
  { code: 'BI', dial: '257', name: 'Burundi' },
  { code: 'KH', dial: '855', name: 'Cambodia' },
  { code: 'CM', dial: '237', name: 'Cameroon' },
  { code: 'CA', dial: '1', name: 'Canada' },
  { code: 'CV', dial: '238', name: 'Cape Verde' },
  { code: 'KY', dial: '1', name: 'Cayman Islands' },
  { code: 'CF', dial: '236', name: 'Central African Republic' },
  { code: 'TD', dial: '235', name: 'Chad' },
  { code: 'CL', dial: '56', name: 'Chile' },
  { code: 'CN', dial: '86', name: 'China' },
  { code: 'CO', dial: '57', name: 'Colombia' },
  { code: 'KM', dial: '269', name: 'Comoros' },
  { code: 'CG', dial: '242', name: 'Congo' },
  { code: 'CD', dial: '243', name: 'Congo (DRC)' },
  { code: 'CK', dial: '682', name: 'Cook Islands' },
  { code: 'CR', dial: '506', name: 'Costa Rica' },
  { code: 'CI', dial: '225', name: "Côte d'Ivoire" },
  { code: 'HR', dial: '385', name: 'Croatia' },
  { code: 'CU', dial: '53', name: 'Cuba' },
  { code: 'CY', dial: '357', name: 'Cyprus' },
  { code: 'CZ', dial: '420', name: 'Czechia' },
  { code: 'DK', dial: '45', name: 'Denmark' },
  { code: 'DJ', dial: '253', name: 'Djibouti' },
  { code: 'DM', dial: '1', name: 'Dominica' },
  { code: 'DO', dial: '1', name: 'Dominican Republic' },
  { code: 'TL', dial: '670', name: 'East Timor' },
  { code: 'EC', dial: '593', name: 'Ecuador' },
  { code: 'EG', dial: '20', name: 'Egypt' },
  { code: 'SV', dial: '503', name: 'El Salvador' },
  { code: 'GQ', dial: '240', name: 'Equatorial Guinea' },
  { code: 'ER', dial: '291', name: 'Eritrea' },
  { code: 'EE', dial: '372', name: 'Estonia' },
  { code: 'SZ', dial: '268', name: 'Eswatini' },
  { code: 'ET', dial: '251', name: 'Ethiopia' },
  { code: 'FK', dial: '500', name: 'Falkland Islands' },
  { code: 'FO', dial: '298', name: 'Faroe Islands' },
  { code: 'FJ', dial: '679', name: 'Fiji' },
  { code: 'FI', dial: '358', name: 'Finland' },
  { code: 'FR', dial: '33', name: 'France' },
  { code: 'GF', dial: '594', name: 'French Guiana' },
  { code: 'PF', dial: '689', name: 'French Polynesia' },
  { code: 'GA', dial: '241', name: 'Gabon' },
  { code: 'GM', dial: '220', name: 'Gambia' },
  { code: 'GE', dial: '995', name: 'Georgia' },
  { code: 'DE', dial: '49', name: 'Germany' },
  { code: 'GH', dial: '233', name: 'Ghana' },
  { code: 'GI', dial: '350', name: 'Gibraltar' },
  { code: 'GR', dial: '30', name: 'Greece' },
  { code: 'GL', dial: '299', name: 'Greenland' },
  { code: 'GD', dial: '1', name: 'Grenada' },
  { code: 'GP', dial: '590', name: 'Guadeloupe' },
  { code: 'GU', dial: '1', name: 'Guam' },
  { code: 'GT', dial: '502', name: 'Guatemala' },
  { code: 'GN', dial: '224', name: 'Guinea' },
  { code: 'GW', dial: '245', name: 'Guinea-Bissau' },
  { code: 'GY', dial: '592', name: 'Guyana' },
  { code: 'HT', dial: '509', name: 'Haiti' },
  { code: 'HN', dial: '504', name: 'Honduras' },
  { code: 'HK', dial: '852', name: 'Hong Kong' },
  { code: 'HU', dial: '36', name: 'Hungary' },
  { code: 'IS', dial: '354', name: 'Iceland' },
  { code: 'IN', dial: '91', name: 'India' },
  { code: 'ID', dial: '62', name: 'Indonesia' },
  { code: 'IR', dial: '98', name: 'Iran' },
  { code: 'IQ', dial: '964', name: 'Iraq' },
  { code: 'IE', dial: '353', name: 'Ireland' },
  { code: 'IL', dial: '972', name: 'Israel' },
  { code: 'IT', dial: '39', name: 'Italy' },
  { code: 'JM', dial: '1', name: 'Jamaica' },
  { code: 'JP', dial: '81', name: 'Japan' },
  { code: 'JO', dial: '962', name: 'Jordan' },
  { code: 'KZ', dial: '7', name: 'Kazakhstan' },
  { code: 'KE', dial: '254', name: 'Kenya' },
  { code: 'KI', dial: '686', name: 'Kiribati' },
  { code: 'XK', dial: '383', name: 'Kosovo' },
  { code: 'KW', dial: '965', name: 'Kuwait' },
  { code: 'KG', dial: '996', name: 'Kyrgyzstan' },
  { code: 'LA', dial: '856', name: 'Laos' },
  { code: 'LV', dial: '371', name: 'Latvia' },
  { code: 'LB', dial: '961', name: 'Lebanon' },
  { code: 'LS', dial: '266', name: 'Lesotho' },
  { code: 'LR', dial: '231', name: 'Liberia' },
  { code: 'LY', dial: '218', name: 'Libya' },
  { code: 'LI', dial: '423', name: 'Liechtenstein' },
  { code: 'LT', dial: '370', name: 'Lithuania' },
  { code: 'LU', dial: '352', name: 'Luxembourg' },
  { code: 'MO', dial: '853', name: 'Macau' },
  { code: 'MG', dial: '261', name: 'Madagascar' },
  { code: 'MW', dial: '265', name: 'Malawi' },
  { code: 'MY', dial: '60', name: 'Malaysia' },
  { code: 'MV', dial: '960', name: 'Maldives' },
  { code: 'ML', dial: '223', name: 'Mali' },
  { code: 'MT', dial: '356', name: 'Malta' },
  { code: 'MH', dial: '692', name: 'Marshall Islands' },
  { code: 'MQ', dial: '596', name: 'Martinique' },
  { code: 'MR', dial: '222', name: 'Mauritania' },
  { code: 'MU', dial: '230', name: 'Mauritius' },
  { code: 'MX', dial: '52', name: 'Mexico' },
  { code: 'FM', dial: '691', name: 'Micronesia' },
  { code: 'MD', dial: '373', name: 'Moldova' },
  { code: 'MC', dial: '377', name: 'Monaco' },
  { code: 'MN', dial: '976', name: 'Mongolia' },
  { code: 'ME', dial: '382', name: 'Montenegro' },
  { code: 'MS', dial: '1', name: 'Montserrat' },
  { code: 'MA', dial: '212', name: 'Morocco' },
  { code: 'MZ', dial: '258', name: 'Mozambique' },
  { code: 'MM', dial: '95', name: 'Myanmar' },
  { code: 'NA', dial: '264', name: 'Namibia' },
  { code: 'NR', dial: '674', name: 'Nauru' },
  { code: 'NP', dial: '977', name: 'Nepal' },
  { code: 'NL', dial: '31', name: 'Netherlands' },
  { code: 'NC', dial: '687', name: 'New Caledonia' },
  { code: 'NZ', dial: '64', name: 'New Zealand' },
  { code: 'NI', dial: '505', name: 'Nicaragua' },
  { code: 'NE', dial: '227', name: 'Niger' },
  { code: 'NG', dial: '234', name: 'Nigeria' },
  { code: 'NU', dial: '683', name: 'Niue' },
  { code: 'KP', dial: '850', name: 'North Korea' },
  { code: 'MK', dial: '389', name: 'North Macedonia' },
  { code: 'MP', dial: '1', name: 'Northern Mariana Islands' },
  { code: 'NO', dial: '47', name: 'Norway' },
  { code: 'OM', dial: '968', name: 'Oman' },
  { code: 'PK', dial: '92', name: 'Pakistan' },
  { code: 'PW', dial: '680', name: 'Palau' },
  { code: 'PS', dial: '970', name: 'Palestine' },
  { code: 'PA', dial: '507', name: 'Panama' },
  { code: 'PG', dial: '675', name: 'Papua New Guinea' },
  { code: 'PY', dial: '595', name: 'Paraguay' },
  { code: 'PE', dial: '51', name: 'Peru' },
  { code: 'PH', dial: '63', name: 'Philippines' },
  { code: 'PL', dial: '48', name: 'Poland' },
  { code: 'PT', dial: '351', name: 'Portugal' },
  { code: 'PR', dial: '1', name: 'Puerto Rico' },
  { code: 'QA', dial: '974', name: 'Qatar' },
  { code: 'RE', dial: '262', name: 'Réunion' },
  { code: 'RO', dial: '40', name: 'Romania' },
  { code: 'RU', dial: '7', name: 'Russia' },
  { code: 'RW', dial: '250', name: 'Rwanda' },
  { code: 'KN', dial: '1', name: 'Saint Kitts and Nevis' },
  { code: 'LC', dial: '1', name: 'Saint Lucia' },
  { code: 'VC', dial: '1', name: 'Saint Vincent and the Grenadines' },
  { code: 'WS', dial: '685', name: 'Samoa' },
  { code: 'SM', dial: '378', name: 'San Marino' },
  { code: 'ST', dial: '239', name: 'São Tomé and Príncipe' },
  { code: 'SA', dial: '966', name: 'Saudi Arabia' },
  { code: 'SN', dial: '221', name: 'Senegal' },
  { code: 'RS', dial: '381', name: 'Serbia' },
  { code: 'SC', dial: '248', name: 'Seychelles' },
  { code: 'SL', dial: '232', name: 'Sierra Leone' },
  { code: 'SG', dial: '65', name: 'Singapore' },
  { code: 'SK', dial: '421', name: 'Slovakia' },
  { code: 'SI', dial: '386', name: 'Slovenia' },
  { code: 'SB', dial: '677', name: 'Solomon Islands' },
  { code: 'SO', dial: '252', name: 'Somalia' },
  { code: 'ZA', dial: '27', name: 'South Africa' },
  { code: 'KR', dial: '82', name: 'South Korea' },
  { code: 'SS', dial: '211', name: 'South Sudan' },
  { code: 'ES', dial: '34', name: 'Spain' },
  { code: 'LK', dial: '94', name: 'Sri Lanka' },
  { code: 'SD', dial: '249', name: 'Sudan' },
  { code: 'SR', dial: '597', name: 'Suriname' },
  { code: 'SE', dial: '46', name: 'Sweden' },
  { code: 'CH', dial: '41', name: 'Switzerland' },
  { code: 'SY', dial: '963', name: 'Syria' },
  { code: 'TW', dial: '886', name: 'Taiwan' },
  { code: 'TJ', dial: '992', name: 'Tajikistan' },
  { code: 'TZ', dial: '255', name: 'Tanzania' },
  { code: 'TH', dial: '66', name: 'Thailand' },
  { code: 'TG', dial: '228', name: 'Togo' },
  { code: 'TO', dial: '676', name: 'Tonga' },
  { code: 'TT', dial: '1', name: 'Trinidad and Tobago' },
  { code: 'TN', dial: '216', name: 'Tunisia' },
  { code: 'TR', dial: '90', name: 'Türkiye' },
  { code: 'TM', dial: '993', name: 'Turkmenistan' },
  { code: 'TC', dial: '1', name: 'Turks and Caicos Islands' },
  { code: 'TV', dial: '688', name: 'Tuvalu' },
  { code: 'UG', dial: '256', name: 'Uganda' },
  { code: 'UA', dial: '380', name: 'Ukraine' },
  { code: 'AE', dial: '971', name: 'United Arab Emirates' },
  { code: 'GB', dial: '44', name: 'United Kingdom' },
  { code: 'US', dial: '1', name: 'United States' },
  { code: 'UY', dial: '598', name: 'Uruguay' },
  { code: 'UZ', dial: '998', name: 'Uzbekistan' },
  { code: 'VU', dial: '678', name: 'Vanuatu' },
  { code: 'VA', dial: '379', name: 'Vatican City' },
  { code: 'VE', dial: '58', name: 'Venezuela' },
  { code: 'VN', dial: '84', name: 'Vietnam' },
  { code: 'VI', dial: '1', name: 'US Virgin Islands' },
  { code: 'YE', dial: '967', name: 'Yemen' },
  { code: 'ZM', dial: '260', name: 'Zambia' },
  { code: 'ZW', dial: '263', name: 'Zimbabwe' },
];

// Emoji flag from an ISO 3166-1 alpha-2 code (regional-indicator symbols).
// Renders as a flag on phones; on some desktop systems it shows two letters.
export function flagEmoji(code: string): string {
  const upper = code.toUpperCase();
  return String.fromCodePoint(
    ...upper
      .split('')
      .map((char) => 0x1f1e6 + (char.charCodeAt(0) - 'A'.charCodeAt(0))),
  );
}

// Default selection for the attendee phone picker. An explicit ISO 3166-1
// alpha-2 country code from configuration is preferred — it is unambiguous. A
// dial code is only used when it identifies exactly one country: some codes
// are shared (e.g. `1` across the whole NANP, `7` between Kazakhstan and
// Russia), and guessing which country the attendee means from an ambiguous
// code would permanently select the wrong default. Falls back to Lebanon (the
// app's primary market).
export function resolveDefaultCountryCode(
  iso?: string,
  dial?: string,
): string {
  if (iso) {
    const match = getCountry(iso.trim().toUpperCase());
    if (match) {
      return match.code;
    }
  }

  const digits = dial?.replace(/\D/g, '');
  if (digits) {
    const matches = COUNTRIES.filter((country) => country.dial === digits);
    if (matches.length === 1) {
      return matches[0].code;
    }
  }

  return 'LB';
}

export function getCountry(code: string): Country | undefined {
  return COUNTRIES.find((country) => country.code === code);
}
